language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_script:
  - mysql -e 'create database IF NOT EXISTS symfony;'
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer selfupdate
  - composer install
  - php app/console doctrine:databa:create --no-interaction --env=test
  - php app/console doctrine:schema:create --no-interaction --env=test
  - php app/console doctrine:fixtures:load --no-interaction --env=test

script:
  - phpunit -c app

notifications:
  email:
    -  marcmorales83@gmail.com
    -  david@flux.cat
    -  marc@teclliure.net

branches:
  only:
    - master
    - devel
