language: php
php:
    - 5.5
    - 5.6

before_script:
  - mysql -e 'create database IF NOT EXISTS symfony;'
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install
  - php app/console doctrine:database:create -n --if-not-exists --env=dev
  - php app/console doctrine:schema:update -n --force --env=dev
  - php app/console doctrine:fixtures:load -n --env=dev

script:
  - phpunit -c app

notifications:
  email:
    -  marcmorales83@gmail.com
    -  david@flux.cat
    -  marc@teclliure.net

branches:
  only:
    - master
    - devel
