services:
    app.abstract_manager:
        abstract:  true
        arguments: [ @doctrine.orm.entity_manager, @validator ]

    app.comment_vote:
        class: Demofony2\AppBundle\Manager\CommentVoteManager
        parent: app.abstract_manager

    app.file_manager:
        class: Demofony2\AppBundle\Manager\FileManager
        arguments: [@vich_uploader.templating.helper.uploader_helper, @liip_imagine.cache.manager, @request_stack]

    app.mail_manager:
        class: Demofony2\AppBundle\Manager\MailManager
        arguments:
         0: @hip_mandrill.dispatcher
         1: @router
         2: %contact_address%
         3: @templating
         4:
            confirmation.template: %fos_user.registration.confirmation.template%
            resetting.template: %fos_user.resetting.email.template%
            from_email:
              confirmation: %fos_user.registration.confirmation.from_email%
              resetting: %fos_user.resetting.email.from_email%
         5: @demofony2_user.repository
         6: @translator
        lazy: true

    app.citizen_forum:
        class: Demofony2\AppBundle\Manager\CitizenForumManager
        parent: app.abstract_manager
        arguments: [ @form.factory, @app.vote_permission_checker, @app.comment_vote ]

    app.process_participation:
        class: Demofony2\AppBundle\Manager\ProcessParticipationManager
        parent: app.abstract_manager
        arguments: [ @form.factory, @app.vote_permission_checker, @app.comment_vote ]

    app.proposal:
        class: Demofony2\AppBundle\Manager\ProposalManager
        parent: app.abstract_manager
        arguments: [ @form.factory, @app.vote_permission_checker,@app.comment_vote ]

    app.pagination:
        class: Demofony2\AppBundle\Manager\PaginationManager
        arguments: [ @knp_paginator, @request_stack ]

    app.statistics:
        class: Demofony2\AppBundle\Manager\StatisticsManager
        arguments: [ @app.statistics_repository, @widop_google_analytics, @widop_google_analytics.query]

    app.statistics_repository:
        class:           Demofony2\AppBundle\Repository\ParticipationStatisticsRepository
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        lazy: true
        arguments:
            - Demofony2\AppBundle\Entity\ParticipationStatistics

    app.user:
         class: Demofony2\AppBundle\Manager\UserManager
         parent: app.abstract_manager
         arguments: [ @fos_user.user_manager]

    app.vote_permission_checker:
        class: Demofony2\AppBundle\Manager\VotePermissionCheckerService
        arguments: [ @doctrine.orm.entity_manager, @validator ]



# KNP menus
    app.menu.frontmenu:
        class: Demofony2\AppBundle\Menu\FrontendMenu
        arguments: [ "@knp_menu.factory", "@translator.default" ]
    app.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: app.menu.frontmenu
        factory_method: createMainMenu
        arguments: [ "@=service('request_stack').getCurrentRequest()" ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: frontend }
