services:
    app.gallery.twig_extension:
        class: Demofony2\AppBundle\Twig\GalleryPathExtension
        public: false
        tags:
            - { name: twig.extension }
    app.image.twig_extension:
        class: Demofony2\AppBundle\Twig\ImagePathExtension
        public: false
        tags:
            - { name: twig.extension }
